config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  namespace :admin do 
    get '/', to: 'home#index'
    resources :posts
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	before_action :authenticate_user!
	def index
		
	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_post, only: %i[show destroy update edit]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
		
	end

	def create
		@post = Post.new(post_params)
		@post.save
		redirect_to admin_posts_path
	end

	def show
		
	end

	def edit
		
	end

	def update
		@post.update(post_params)
		redirect_to admin_post_path(@post)
	end

	def destroy
		
	end

	def find_post
		@post = Post.find(params[:id])
	end
	private
	def post_params
		params.require(:post).permit(:title, :content)		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/index.html.erb
<h1>Hello Admin</h1>

app/views/admin/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 mx-auto">
			<%= form_for [:admin, @post] do |f| %>
				<div class="form-group mb-2">
					<label class="form-label">Title</label>
					<%= f.text_field :title, class: 'form-control' %>
				</div>
				<div class="form-group mb-2">
					<label class="form-label">Content</label>
					<%= f.text_area :content, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.submit class: 'form-control btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<%= link_to 'New Post', new_admin_post_path(), class: 'btn btn-primary m-2 text-white' %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 mx-auto">
			<table class="table table-border table-hover">
				<thead class="table-dark">
					<tr>
						<th>Title</th>
						<th>Content</th>
						<th>Edit</th>
						<th>Delete</th>
					</tr>
				</thead>
				<tbody>
					<% @posts.each do |post| %>
						<tr>
							<td><%= link_to post.title, admin_post_path(post) %></td>
							<td><%= sanitize post.content.truncate(200, separator: ' ')  %></td>
							<td><%= link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-info' %></td>
							<td><%= button_to 'Delete', [:admin, post], class: 'btn btn-danger', method: :delete %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/admin/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 mx-auto">
			<%= form_for [:admin, @post] do |f| %>
				<div class="form-group mb-2">
					<label class="form-label">Title</label>
					<%= f.text_field :title, class: 'form-control' %>
				</div>
				<div class="form-group mb-2">
					<label class="form-label">Content</label>
					<%= f.text_area :content, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.submit class: 'form-control btn btn-primary' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 mx-auto">
		  <h2><%= sanitize @post.title %></h2>
		  <p><%= sanitize @post.content %></p>
		  <%= link_to "Edit", edit_admin_post_path(@post), class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Posts", admin_posts_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", admin_posts_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Posts", admin_posts_path, class: "nav-link text-white" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= if current_user %>
          
        <% else %>
        <% end %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_registration_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if controller_path =~ /^admin\// %>
      <%= render "admin/shared/header" %>
    <% else %>
      <%= render 'shared/header' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_registration_path, class: "btn btn-success mx-3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>